### ISSUE TITLE
Modify Alphanumeric Sorting in ls Applet to work for all Array Lists

### ISSUE THREAD

**Issue by jcharbon-nd** [pbui-project/pbui-main#74]
The current alphanumeric sorting functions used in ls.zig are only applicable for that applet as the sorting function accepts only a specific type of Array List and also prints the list out in ls format. Rewrite these functions (the sorting function and string compare function) to take any Array List and return it sorted alphanumerically.

**Comment by sambattalio** [comment]
Hmm maybe one could just use std.sort w/ the comparator you made for generalization https://github.com/ziglang/zig/blob/1e23a3cd9162df098a302f22d70f2ac50b5eae21/lib/std/sort.zig#L171?

something like
`std.sort.sort(std.fs.Dir.Entry, comparator);`

**Comment by sambattalio** [comment]
Yea, looks as though it is already generalized, though only for ArrayLists of []u8! Of non-array type it looks like the std.sort library has ascending and descending comparators
