### ISSUE TITLE
Change to MIT License

### ISSUE THREAD

**Issue by AndroidKitKat** [pbui-project/pbui-main#77]
Just saw this comment on Reddit: https://www.reddit.com/r/Zig/comments/g1umkx/small_linux_userland_built_in_zig/fnhqfac/

I want the project to be open for anyone to use without worrying of our license. 

Thoughts?

**Comment by zmenciso** [comment]
I agree wholeheartedly--maybe we should switch to MIT?

**Comment by sambattalio** [comment]
MIT++

**Comment by AndroidKitKat** [comment]
I'm also on board for MIT. Need to talk to @eamonlm, @jcharbon-nd, and @kwjw still.

**Comment by sambattalio** [comment]
dont forget @gabrielsimoes. Would you mind if we relicensed your code?

**Comment by gabrielsimoes** [comment]
> dont forget @gabrielsimoes. Would you mind if we relicensed your code?

No problem at all, MIT all the way

**Comment by ghost** [comment]
Agreed to MIT.
